server:
  port: 8081

spring:
  application:
    name: hadp-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    deserialization:
      fail-on-unknown-properties: false

hbase:
  zookeeper:
    quorum: localhost

logging:
  level:
    com.hadp: DEBUG
    org.apache.hadoop: WARN
    org.apache.hbase: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
